#!/usr/bin/env bash
# Submission build step, copied verbatim into the vendored-source zip by
# tools/package_submission.py. The judge runs it once at intake, with no
# network (RULES.md §08), then never again — matches only ever run run.sh.
#
# It lives here rather than beside run.sh for two reasons. The bot directory
# layout in rewrite-plan §10 does not carry one — run.sh rebuilds itself when
# the sources move, so a local build.sh would be dead weight. And
# `matchup.py::build_agent` runs any build.sh it finds next to a run.sh, then
# crashes formatting the log line for a path outside the submodule
# (`build.relative_to(REPO_ROOT)`, unguarded where the identical call in
# `spawn_agent` is guarded) — so a build.sh in the bot directory breaks the
# repo's own verification gate.
#
# `--offline` is not belt-and-braces, it is the point: without it cargo would
# try to reach crates.io, and a build that only works with a network is a
# build that fails at intake. Every dependency has to be under vendor/ with
# .cargo/config.toml redirecting the registry there. Today there are none, so
# the flag proves that claim rather than merely asserting it.
#
# The zip's copy of this file is generated by tools/package_submission.py; the
# static-binary variant replaces it with a no-op (rewrite-plan §9, R4).
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"

# `cd`, not just `--manifest-path`. Cargo discovers `.cargo/config.toml` by
# walking up from the **working directory**, not from the manifest, and that
# file is what sets `target-cpu=x86-64-v3`. Building from the wrong cwd
# produces a baseline x86-64 binary with no FMA instruction — where every
# `f32::mul_add` in the inference kernels becomes a call to libm's `fmaf()`.
# Measured on a one-core x86 container: 277 ms per forward instead of 5.6 ms,
# a 49x pessimisation that fails silently, builds fine, and would blow the
# 150 ms deadline on every move of every game.
cd "$DIR"
cargo build --release --offline --locked --manifest-path "$DIR/Cargo.toml"
echo "[build] $(ls -l "$DIR/target/release/morpheus-rs")"
