"""
Package a Rust bot from ``bots/<name>/`` into a submission zip, and prove the
archive before it ships.

One archive comes out — sources, ``Cargo.lock``, vendored crates, and a
``build.sh`` running ``cargo build --release --offline`` — and the judge
compiles it at intake on its own toolchain. It is named
``<bot_id>-<content_hash>.zip`` through :func:`arena.bundle.default_output_path`,
the same call the Python bundles use, so an archive says on its face which
rated program it holds and two builds of different code cannot land on one
path. It is audited against the judge's limits through
:func:`arena.bundle.check_limits` — again the same code path as the Python bots,
so the two cannot drift — and then smoke-tested by extracting it, running its
``build.sh``, and driving scripted frames through its ``run.sh``.

This module is the shared half. Everything a bot differs in lives in a
:class:`RustBotSpec`, and each bot's ``tools/package_submission.py`` is that
spec plus ``raise SystemExit(main(SPEC))``. The split exists because a second
hand-written copy of this file would drift from the first within one change to
the judge's limits.

It sits in ``arena/`` rather than ``bots/_common/`` deliberately: the content
hash walk never leaves ``bots/``, so a shared packager here is outside every
bot's rated identity by construction, while ``bots/_common/`` is inside the
Python bots' closures.

**Nothing here may assume the shape of a dependency graph.** morpheus-rs vendors
zero crates and joe-rs vendors ninety-three; the file count is reported and
:func:`arena.bundle.check_limits` is the only enforcement.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import zipfile
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path

from arena.bundle import (
    MAX_FILES,
    MAX_UNPACKED_BYTES,
    MAX_ZIP_BYTES,
    BundleError,
    _ZIP_DATE,
    check_limits,
    default_output_path,
)
from arena.records.fingerprint import bot_content_hash
from arena.records.store import REPO_ROOT

REPO = REPO_ROOT

# The dev-time Rust minifier. Built on the packaging host, where a network
# exists; never shipped, never linked into a bot. Shared, so a second Rust bot
# does not reach into the first one's private tooling.
MINIFY_DIR = REPO / "tools" / "rust-minify"
MINIFY_BIN = MINIFY_DIR / "target" / "release" / "rust-minify"

# Ships in the zip. The judge never reads it; a human comparing a rated result
# on generals.bot against a row in data/bot_versions/<bot>.json does, and
# without it "which program is playing up there" is answerable only by
# rebuilding and hoping. Deliberately carries no timestamp: the zip is
# byte-reproducible from the sources, and a clock in it would end that.
PROVENANCE_NAME = "SUBMISSION.json"

# The `.cargo/config.toml` that goes in the vendored zip. The source
# replacement is what makes `--offline` work: cargo resolves every dependency
# out of `vendor/` instead of reaching for crates.io.
CARGO_CONFIG_VENDORED = """# Generated by tools/package_submission.py — do not edit in the zip.
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=x86-64-v3"]
"""


class PackageError(RuntimeError):
    """The submission cannot be built, or failed its own smoke test."""


@dataclass(frozen=True)
class RustBotSpec:
    """Everything one Rust bot differs from another in, and nothing else.

    A field here is a fact about a bot that the packager needs. A behaviour
    that both bots share belongs in the functions below, not in a flag.

    ``rust-toolchain.toml`` appears in no field on purpose, and that omission
    is the whole mechanism keeping it out of the zip: it pins an exact patch
    release, and a sandbox whose stable toolchain is any other patch would try
    to download the pinned one over a network that does not exist at intake.
    The pin is a development-side guarantee, not a submission member.
    ``tests/test_rust_bundle.py`` asserts the omission so it stays a rule
    rather than a comment.
    """

    bot_id: str
    binary: str
    bot_dir: Path
    #: `.rs` trees compiled from. Everything under them ships, `target/` aside.
    source_trees: tuple[str, ...]
    #: Manifest key naming the artifact file that ships, and the key holding
    #: its sha256. The two bots' manifests are different schemas, and reading
    #: the wrong one puts a digest in SUBMISSION.json that a human will
    #: compare against a file that is not in the zip.
    artifact_file_key: str
    artifact_sha_key: str
    run_sh: str
    #: Dotted paths into the artifact manifest, merged into SUBMISSION.json
    #: under the key on the left.
    provenance_fields: Mapping[str, str]
    provenance_note: str
    #: Handshake plus frames fed to the extracted `run.sh`, and how many
    #: replies must come back.
    smoke_input: str
    smoke_expected_lines: int
    #: Fail a bundle whose every smoke reply is a pass. Only meaningful when
    #: `smoke_input` is a position where passing is the wrong answer.
    smoke_reject_all_pass: bool
    gate_opponent_default: str
    source_members: tuple[str, ...] = ("Cargo.toml", "Cargo.lock")
    config_members: tuple[str, ...] = ()
    artifact_dir: str = "artifact"
    cargo_config: str = CARGO_CONFIG_VENDORED
    #: Vendor the dependency graph and ship `.cargo/config.toml`. `False` ships
    #: a **prebuilt** binary instead through `extra_files`, which deletes the
    #: judge's compile step and everything that can go wrong inside it — the
    #: build's disk, memory, wall time, and its dependence on whatever
    #: toolchain the sandbox happens to have.
    vendor: bool = True
    #: `(bot-relative path, arcname, mode)` shipped verbatim. The prebuilt
    #: binary rides here, at mode 0o755.
    extra_files: tuple[tuple[str, str, int], ...] = ()
    #: Run the packager's own smoke test. A bundle carrying a foreign-arch
    #: binary cannot be smoked on the packaging host — an x86_64 musl
    #: executable does not run on arm64 macOS — so it is verified remotely
    #: instead, and the reason is printed rather than the step silently
    #: passing.
    local_smoke: bool = True
    local_smoke_skip_reason: str = ""
    #: Bot-relative, and deliberately **not** beside `run.sh`:
    #: `matchup.py::build_agent` executes any `build.sh` it finds next to a
    #: `run.sh` and then crashes formatting `build.relative_to(REPO_ROOT)` for
    #: a path outside the submodule, which breaks the repo's own gate.
    build_sh: str = "tools/submission/build.sh"
    #: `(subcommand,)` when the binary has an intake self-test, `None` when it
    #: does not. `None` skips both the step and the parse, so turning one on
    #: later is a spec edit plus a Rust subcommand, not a packager change.
    selfcheck_argv: tuple[str, ...] | None = None
    #: Artifact-dir-relative files that stay OUT of the zip. For a packed
    #: artifact (joe-net-v2), the safetensors is reconstructed by build.sh at
    #: intake and must not ride along at 54 MB.
    artifact_exclude: tuple[str, ...] = ()
    #: Arcnames written uncompressed (ZIP_STORED). Entropy-coded artifact
    #: members gain nothing from deflate; storing them keeps the packager's
    #: reported zip size equal to the member size.
    stored_members: tuple[str, ...] = ()
    selfcheck_keys: frozenset[str] = frozenset()
    minify_dir: Path = MINIFY_DIR
    minify_bin: Path = MINIFY_BIN

    @property
    def build_sh_path(self) -> Path:
        return self.bot_dir / self.build_sh

    @property
    def artifact_root(self) -> Path:
        return self.bot_dir / self.artifact_dir


def _git(*args: str) -> str:
    result = subprocess.run(["git", *args], cwd=str(REPO), capture_output=True, text=True)
    return result.stdout.strip() if result.returncode == 0 else ""


def _dotted(payload: dict, path: str) -> object:
    """Walk `a.b.c` through nested dicts; missing anywhere is `""`.

    Absent rather than fatal, because the manifest keys that matter — the file
    that ships and its digest — are checked in `_artifact_members`, which runs
    first and raises. What comes through here is provenance for a human, and a
    blank field is a better failure than an unpackageable bot.
    """
    node: object = payload
    for part in path.split("."):
        if not isinstance(node, dict) or part not in node:
            return ""
        node = node[part]
    return node


def _provenance(spec: RustBotSpec, minify_stats: dict | None = None) -> bytes:
    manifest = json.loads((spec.artifact_root / "manifest.json").read_text())
    payload: dict = {
        "bot_id": spec.bot_id,
        "minified": bool((minify_stats or {}).get("minified")),
        "content_hash": bot_content_hash(spec.bot_dir / "run.sh"),
        "git_commit": _git("rev-parse", "HEAD"),
        "git_dirty": bool(_git("status", "--porcelain", "--", f"bots/{spec.bot_id}")),
        "note": spec.provenance_note,
    }
    for key, path in spec.provenance_fields.items():
        payload[key] = _dotted(manifest, path)
    # A prebuilt binary is the program itself, so the zip must say which bytes
    # it carries. Without this, "which build is playing" is answerable only by
    # rebuilding — and the whole point of shipping a binary is that the judge
    # never builds.
    for rel, arcname, _mode in spec.extra_files:
        path = spec.bot_dir / rel
        if path.is_file():
            payload[f"{arcname}_sha256"] = hashlib.sha256(path.read_bytes()).hexdigest()
    return (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode()


@dataclass
class Package:
    content_hash: str
    zip_path: Path
    zip_sha256: str
    zip_bytes: int
    unpacked_bytes: int
    file_count: int
    smoked: bool
    smoke_note: str
    selfcheck: dict[str, str] = field(default_factory=dict)


def _cargo_env() -> dict[str, str]:
    """Environment with cargo on PATH, wherever rustup put it."""
    env = os.environ.copy()
    cargo_bin = Path.home() / ".cargo" / "bin"
    if cargo_bin.is_dir():
        env["PATH"] = f"{cargo_bin}{os.pathsep}{env.get('PATH', '')}"
    return env


def _run(command: list[str], cwd: Path, env: dict[str, str] | None = None) -> str:
    result = subprocess.run(
        command, cwd=str(cwd), env=env or _cargo_env(), capture_output=True, text=True
    )
    if result.returncode != 0:
        raise PackageError(
            f"{' '.join(command)} failed in {cwd}:\n{result.stdout}\n{result.stderr}"
        )
    return result.stdout


def _ensure_minifier(spec: RustBotSpec) -> Path:
    """Build the minifier crate if it is not already built, and return it."""
    if not spec.minify_bin.is_file():
        _run(["cargo", "build", "--release"], cwd=spec.minify_dir)
    if not spec.minify_bin.is_file():
        raise PackageError(f"no minifier at {spec.minify_bin}")
    return spec.minify_bin


def strip_line_comments(text: str) -> str:
    """
    Drop whole-line `#` comments from a shell script or a TOML file.

    The launchers and `build.sh` carry as much reasoning as the Rust does — why
    `cd` before `cargo build`, what a missing FMA costs, why intake fails loudly
    — and none of it is needed to run them. This is the shell half of what
    `tools/rust-minify` does to the `.rs` members, and it runs under the same
    rule: on the way into the zip only.

    **Whole-line only, and the shebang stays.** A trailing `# …` after code is
    left alone, because a line-based rule cannot tell a comment from a `#`
    inside a string or from `${var#prefix}`, and a launcher that stops working
    is a forfeit. Blank runs left behind by removed blocks are collapsed so the
    result reads like a script rather than a sieve.
    """
    kept: list[str] = []
    for index, line in enumerate(text.splitlines()):
        stripped = line.strip()
        if index == 0 and stripped.startswith("#!"):
            kept.append(line)
            continue
        if stripped.startswith("#"):
            continue
        if not stripped and (not kept or not kept[-1].strip()):
            continue
        kept.append(line)
    return "\n".join(kept).rstrip("\n") + "\n"


def _shell(text: str, *, minify: bool) -> bytes:
    return (strip_line_comments(text) if minify else text).encode()


def _minify_rust(spec: RustBotSpec, source: bytes, arcname: str) -> bytes:
    """
    One `.rs` file, stripped of everything the judge does not need.

    Same discipline as `arena/bundle.py`: the rewrite happens **on the way into
    the zip only** and the repo file is never touched. A failure is fatal
    rather than a fallback to the original text — shipping the un-minified file
    while reporting a minified bundle is the one outcome worse than not
    minifying at all.
    """
    result = subprocess.run([str(_ensure_minifier(spec))], input=source, capture_output=True)
    if result.returncode != 0:
        raise PackageError(
            f"minifying {arcname}: {result.stderr.decode(errors='replace').strip()}"
        )
    return result.stdout


def _artifact_members(spec: RustBotSpec) -> list[tuple[Path, str]]:
    """
    (path, arcname) for the weights, checked against their own manifest.

    The digest is verified here as well as by the loader, and for two bots it
    is the last automatic detector of two different faults. A morpheus seat
    that cannot load its weights passes every turn rather than exiting, so
    nothing downstream sees the difference. And a joe artifact is gitignored,
    so `git_dirty` in SUBMISSION.json cannot see a stale one. **Keep this
    fatal.**
    """
    root = spec.artifact_root
    manifest_path = root / "manifest.json"
    if not manifest_path.is_file():
        raise PackageError(
            f"missing {spec.artifact_dir}/manifest.json; run tools/convert_artifact.py"
        )
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    for key in (spec.artifact_file_key, spec.artifact_sha_key):
        if key not in manifest:
            raise PackageError(f"{manifest_path} has no {key!r}")
    weights = root / manifest[spec.artifact_file_key]
    if not weights.is_file():
        raise PackageError(
            f"manifest names {manifest[spec.artifact_file_key]}, which is missing"
        )
    digest = hashlib.sha256(weights.read_bytes()).hexdigest()
    if digest != manifest[spec.artifact_sha_key]:
        raise PackageError(
            f"{weights.name} hashes to {digest}, manifest says "
            f"{manifest[spec.artifact_sha_key]}"
        )
    excluded = {root / rel for rel in spec.artifact_exclude}
    return [
        (path, str(path.relative_to(spec.bot_dir)))
        for path in sorted(root.rglob("*"))
        if path.is_file() and path not in excluded
    ]


def _iter_source_files(spec: RustBotSpec, *, minify: bool) -> tuple[list[tuple[str, bytes]], dict]:
    """
    (arcname, bytes) for everything the archive compiles from.

    Returns contents rather than paths because `.rs` members are rewritten on
    the way in — comments and doc comments stripped — and the repo file is
    never touched. The second return value is what the rewrite cost, so
    "was this bundle minified" is a number rather than a flag.
    """
    members: list[tuple[str, bytes]] = []
    for name in spec.source_members:
        path = spec.bot_dir / name
        if not path.is_file():
            raise PackageError(f"missing {name}; run cargo build once first")
        members.append((name, path.read_bytes()))
    for name in spec.config_members:
        path = spec.bot_dir / name
        if not path.is_file():
            raise PackageError(f"missing {name}; the bot would play placeholder knobs")
        members.append((name, path.read_bytes()))

    before = after = 0
    for tree in spec.source_trees:
        root = spec.bot_dir / tree
        if not root.is_dir():
            raise PackageError(f"missing {tree}/")
        for path in sorted(root.rglob("*")):
            if not path.is_file() or "target" in path.parts:
                continue
            arcname = str(path.relative_to(spec.bot_dir))
            data = path.read_bytes()
            if minify and path.suffix == ".rs":
                before += len(data)
                data = _minify_rust(spec, data, arcname)
                after += len(data)
            members.append((arcname, data))

    for path, arcname in _artifact_members(spec):
        members.append((arcname, path.read_bytes()))
    return members, {
        "minified": bool(minify and before),
        "rust_bytes_before": before,
        "rust_bytes_after": after,
    }


def _write_entry(
    zf: zipfile.ZipFile, arcname: str, data: bytes, *, mode: int, stored: bool = False
) -> None:
    info = zipfile.ZipInfo(arcname, date_time=_ZIP_DATE)
    info.compress_type = zipfile.ZIP_STORED if stored else zipfile.ZIP_DEFLATED
    # The judge executes run.sh and build.sh; a zip that loses the executable
    # bit produces a "permission denied" at intake that looks like a bot bug.
    info.external_attr = (mode & 0o7777) << 16
    zf.writestr(info, data)


def _vendor(spec: RustBotSpec, workdir: Path) -> tuple[Path, int]:
    """
    Vendor the dependency graph. Returns (dir, file count).

    The count is reported, never judged. It is zero for a bot with no
    dependencies and 3,946 for one built on candle, and which limit binds
    differs with it: `arena.bundle.check_limits` is the only enforcement, so a
    Rust bundle and a Python one are held to the same numbers.
    """
    vendor_dir = workdir / "vendor"
    vendor_dir.mkdir(parents=True, exist_ok=True)
    _run(["cargo", "vendor", "--versioned-dirs", str(vendor_dir)], cwd=spec.bot_dir)
    return vendor_dir, sum(1 for p in vendor_dir.rglob("*") if p.is_file())


def build_vendored(
    spec: RustBotSpec, out_path: Path, workdir: Path, *, minify: bool
) -> tuple[Path, int, dict]:
    vendor_dir, vendor_files = _vendor(spec, workdir) if spec.vendor else (None, 0)
    build_sh = spec.build_sh_path.read_text()
    members, minify_stats = _iter_source_files(spec, minify=minify)

    with zipfile.ZipFile(out_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        _write_entry(zf, "run.sh", _shell(spec.run_sh, minify=minify), mode=0o755)
        _write_entry(zf, "build.sh", _shell(build_sh, minify=minify), mode=0o755)
        if spec.vendor:
            # Only meaningful beside a `vendor/`: the file's whole job is to
            # point cargo's registry at it.
            _write_entry(
                zf, ".cargo/config.toml", _shell(spec.cargo_config, minify=minify), mode=0o644
            )
        for arcname, data in members:
            _write_entry(zf, arcname, data, mode=0o644, stored=arcname in spec.stored_members)
        for rel, arcname, mode in spec.extra_files:
            path = spec.bot_dir / rel
            if not path.is_file():
                raise PackageError(f"missing {rel}; the bundle would ship no binary")
            _write_entry(zf, arcname, path.read_bytes(), mode=mode)
        _write_entry(zf, PROVENANCE_NAME, _provenance(spec, minify_stats), mode=0o644)
        if vendor_dir is not None:
            for path in sorted(vendor_dir.rglob("*")):
                if path.is_file():
                    arcname = f"vendor/{path.relative_to(vendor_dir)}"
                    _write_entry(zf, arcname, path.read_bytes(), mode=0o644)
    return out_path, vendor_files, minify_stats


def _selfcheck_facts(spec: RustBotSpec, stdout: str) -> dict[str, str]:
    """The `key value` lines the binary's selfcheck prints, as a dict."""
    facts: dict[str, str] = {}
    if spec.selfcheck_argv is None:
        return facts
    for line in stdout.splitlines():
        head, _, tail = line.partition(" ")
        if head in spec.selfcheck_keys:
            facts[head] = tail.strip()
    return facts


def _is_pass(line: str) -> bool:
    """`<pass> <row> <col> <dir> <split>`, where pass 1 is "skip this turn"."""
    return line.split()[0] == "1"


def smoke(spec: RustBotSpec, zip_path: Path) -> tuple[bool, str, dict[str, str]]:
    """
    Extract the archive, run its build.sh, and speak the protocol to run.sh.

    This is the part that makes packaging a check rather than a hope: it runs
    the submitted bytes, from a directory with no repo around them, exactly as
    the judge will.

    **A well-formed reply is not always evidence of a working bot**, and how
    much it is worth differs per bot. **Both** seats now pass every turn rather
    than exiting when they cannot load — the deliberate trade, since the judge
    forfeits on an early exit — so this test once scored a bundle with
    `artifact/` deleted as two well-formed actions. `selfcheck` is what closes
    that, and its output is parsed here rather than merely allowed to pass.

    joe-rs used to be the exception, exiting 1 on a load failure so that a
    broken artifact produced *no* replies and was caught by the line count
    alone. That detector was worth less than the forfeits it cost, so it now
    carries a `selfcheck` too. What it still adds beyond morpheus is
    `smoke_reject_all_pass`, on frames where passing is the wrong answer, so a
    seat that answers everything with a skip fails here as well.
    """
    with tempfile.TemporaryDirectory(prefix=f"{spec.bot_id}-smoke-") as tmp:
        root = Path(tmp)
        with zipfile.ZipFile(zip_path) as zf:
            zf.extractall(root)
        for name in ("run.sh", "build.sh"):
            (root / name).chmod(0o755)

        build = subprocess.run(
            ["bash", str(root / "build.sh")],
            cwd=str(root),
            env=_cargo_env(),
            capture_output=True,
            text=True,
        )
        facts = _selfcheck_facts(spec, build.stdout)
        if build.returncode != 0:
            return False, f"build.sh failed: {(build.stderr or build.stdout)[-600:]}", facts
        if spec.selfcheck_argv is not None and facts.get("selfcheck") != "ok":
            return False, "build.sh did not run selfcheck", facts

        play = subprocess.run(
            ["bash", str(root / "run.sh")],
            cwd=str(root),
            input=spec.smoke_input,
            capture_output=True,
            text=True,
            timeout=120,
        )
        lines = [line for line in play.stdout.strip().splitlines() if line.strip()]
        if len(lines) != spec.smoke_expected_lines:
            return (
                False,
                (
                    f"run.sh replied {len(lines)} line(s), expected "
                    f"{spec.smoke_expected_lines}: {play.stdout!r} {play.stderr[-300:]}"
                ),
                facts,
            )
        for line in lines:
            parts = line.split()
            if len(parts) != 5 or not all(p.lstrip("-").isdigit() for p in parts):
                return False, f"malformed reply {line!r}", facts
        if spec.smoke_reject_all_pass and all(_is_pass(line) for line in lines):
            return (
                False,
                (
                    "every smoke reply was a pass, on frames where passing is the "
                    "wrong answer — the seat is running but not deciding"
                ),
                facts,
            )
        if spec.selfcheck_argv is not None:
            note = (
                f"selfcheck ok (fma={facts.get('hardware_fma')}, "
                f"decided `{facts.get('decision')}` in {facts.get('decide_ms')} ms), "
                f"replied {len(lines)} well-formed actions"
            )
        else:
            moves = sum(1 for line in lines if not _is_pass(line))
            note = f"replied {len(lines)} well-formed actions, {moves} of them a move"
        return True, note, facts


def package(
    spec: RustBotSpec, *, out_dir: Path, force: bool, run_smoke: bool, minify: bool = True
) -> Package:
    out_dir.mkdir(parents=True, exist_ok=True)
    content_hash = bot_content_hash(spec.bot_dir / "run.sh")
    # `arena.bundle`'s own naming, so a Rust bundle and a Python one are the
    # same kind of object on disk: `<bot_id>-<content_hash>.zip`. The hash is
    # the rated identity, so an archive names the program it holds and two
    # builds of different code cannot collide on one path.
    out_path = default_output_path(spec.bot_id, content_hash)
    if out_dir != out_path.parent:
        out_path = out_dir / out_path.name
    if out_path.exists() and not force:
        raise PackageError(f"{out_path} exists (pass --force to overwrite)")

    vendor_files = 0
    minify_stats: dict = {}
    with tempfile.TemporaryDirectory(prefix=f"{spec.bot_id}-pkg-") as tmp:
        # Built beside the destination and moved into place only on success.
        # Writing straight to `out_path` leaves a **partial archive** when a
        # member check fails mid-zip, and nothing downstream can tell one from
        # a finished bundle: an aborted static build left a four-file zip with
        # no weights in `data/bundles/`, which the Modal smoke then dutifully
        # shipped to an x86 container.
        staged = Path(tmp) / out_path.name
        _, vendor_files, minify_stats = build_vendored(spec, staged, Path(tmp), minify=minify)
        out_path.unlink(missing_ok=True)
        shutil.move(str(staged), str(out_path))

    zip_bytes, unpacked_bytes, file_count = check_limits(out_path)
    smoked, note, facts = (False, "skipped", {})
    if run_smoke and not spec.local_smoke:
        note = f"skipped: {spec.local_smoke_skip_reason}"
    elif run_smoke:
        smoked, note, facts = smoke(spec, out_path)
    note = f"{note}; {vendor_files} vendored file(s)"
    if minify_stats.get("minified"):
        note = (
            f"{note}; sources minified {minify_stats['rust_bytes_before']} -> "
            f"{minify_stats['rust_bytes_after']} B"
        )

    return Package(
        content_hash=content_hash,
        zip_path=out_path,
        # The zip is byte-reproducible from the sources (fixed member dates,
        # sorted members, no clock in SUBMISSION.json), so this digest answers
        # "are the bytes I submitted the bytes I still have" without a rebuild.
        zip_sha256=hashlib.sha256(out_path.read_bytes()).hexdigest(),
        zip_bytes=zip_bytes,
        unpacked_bytes=unpacked_bytes,
        file_count=file_count,
        smoked=smoked,
        smoke_note=note,
        selfcheck=facts,
    )


def gate(spec: RustBotSpec, zip_path: Path, *, opponent: str, seed: int, keep: bool) -> dict:
    """
    Play the AGENTS.md verification gate with the *submitted* bytes.

    Every gate before this one drove `bots/<bot>/run.sh` — the repo launcher,
    which builds from the working tree and finds the artifact by walking up
    from `target/`. The zip has a different launcher, a different directory
    shape and a build step, and none of that was ever put in front of a
    competition match. A frame script cannot substitute: it never reaches a
    belief update, an admission decision, or a deathtouch turn.

    **`build.sh` is run and then deleted**, which is a deviation worth stating
    rather than hiding. The judge's sequence is exactly that — build once at
    intake, then spawn `run.sh` for every game and never look at `build.sh`
    again (RULES.md §08) — so removing it models the end of intake. It is also
    the only way this gate can run: `matchup.py::build_agent` executes any
    `build.sh` beside a `run.sh` and formats its log line with
    `build.relative_to(REPO_ROOT)`, unguarded, where `REPO_ROOT` is the
    *submodule's* root. Every path outside `competition-module/` raises, so a
    submission-shaped directory crashes the gate before the first move no
    matter where it is extracted. What goes untested is `build_agent`, which
    the judge does not have.
    """
    root = REPO / "data" / "bundles" / f"extracted-{zip_path.stem}"
    if root.exists():
        shutil.rmtree(root)
    root.mkdir(parents=True)
    with zipfile.ZipFile(zip_path) as zf:
        zf.extractall(root)
    for name in ("run.sh", "build.sh"):
        (root / name).chmod(0o755)

    build = subprocess.run(
        ["bash", str(root / "build.sh")],
        cwd=str(root),
        env=_cargo_env(),
        capture_output=True,
        text=True,
        timeout=60 * 30,
    )
    if build.returncode != 0:
        if not keep:
            shutil.rmtree(root, ignore_errors=True)
        return {
            "opponent": opponent,
            "seed": seed,
            "returncode": build.returncode,
            "tail": (build.stdout + build.stderr).strip().splitlines()[-12:],
        }
    (root / "build.sh").unlink()

    result = subprocess.run(
        [
            sys.executable,
            str(REPO / "competition-module" / "competition" / "matchup.py"),
            str(root / "run.sh"),
            str(REPO / "bots" / opponent / "run.sh"),
            "--mode",
            "competition",
            "--seed",
            str(seed),
        ],
        cwd=str(REPO),
        # The Python side of the pairing needs an interpreter with the repo's
        # dependencies; `matchup.py` spawns `run.sh`, which honours PYTHON.
        # Absolute, not relative: a relative value silently BrokenPipes the
        # Python seat.
        env={**_cargo_env(), "PYTHON": str(REPO / ".venv" / "bin" / "python")},
        capture_output=True,
        text=True,
        timeout=60 * 30,
    )
    tail = (result.stdout + result.stderr).strip().splitlines()[-12:]
    if not keep:
        shutil.rmtree(root, ignore_errors=True)
    return {"opponent": opponent, "seed": seed, "returncode": result.returncode, "tail": tail}


def main(spec: RustBotSpec, argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=f"Package {spec.bot_id} into a generals.bot submission zip."
    )
    parser.add_argument("--out-dir", type=Path, default=default_output_path(spec.bot_id).parent)
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--no-smoke", action="store_true")
    parser.add_argument(
        "--no-minify",
        action="store_true",
        help="ship the .rs sources verbatim, comments and all. Use when a judge "
        "traceback has to be read against real line numbers.",
    )
    parser.add_argument(
        "--gate",
        action="store_true",
        help="play the AGENTS.md competition gate with the extracted bundle "
        "(minutes, not seconds)",
    )
    parser.add_argument("--gate-opponent", default=spec.gate_opponent_default)
    parser.add_argument("--gate-seed", type=int, default=0)
    parser.add_argument(
        "--keep-extracted",
        action="store_true",
        help="leave data/bundles/extracted-* in place after the gate",
    )
    args = parser.parse_args(argv)

    failures: list[dict] = []
    try:
        built = package(
            spec,
            out_dir=args.out_dir,
            force=args.force,
            run_smoke=not args.no_smoke,
            minify=not args.no_minify,
        )
    except (PackageError, BundleError) as exc:
        print(json.dumps({"package": None, "failures": [{"error": str(exc)}]}, indent=2))
        return 1

    row: dict = {
        "content_hash": built.content_hash,
        "zip": str(built.zip_path),
        "zip_sha256": built.zip_sha256,
        "zip_bytes": built.zip_bytes,
        "zip_limit": MAX_ZIP_BYTES,
        "unpacked_bytes": built.unpacked_bytes,
        "unpacked_limit": MAX_UNPACKED_BYTES,
        "files": built.file_count,
        "files_limit": MAX_FILES,
        "smoked": built.smoked,
        "smoke": built.smoke_note,
        "selfcheck": built.selfcheck,
    }
    # A smoke that ran and did not pass is a failed packaging run rather than a
    # row in a table nobody reads. `--no-smoke` is the caller saying they know.
    if not args.no_smoke and spec.local_smoke and not built.smoked:
        failures.append({"error": f"smoke test did not pass: {built.smoke_note}"})
    if args.gate and built.smoked:
        try:
            row["gate"] = gate(
                spec,
                built.zip_path,
                opponent=args.gate_opponent,
                seed=args.gate_seed,
                keep=args.keep_extracted,
            )
        except (subprocess.SubprocessError, OSError) as exc:
            row["gate"] = {"error": str(exc)}
        if row["gate"].get("returncode") != 0:
            failures.append({"error": "competition gate failed"})

    print(json.dumps({"package": row, "failures": failures}, indent=2))
    return 1 if failures else 0
