#!/usr/bin/env python3
"""Package morpheus-rs for generals.bot, in both variants, and prove each one.

    python bots/morpheus-rs/tools/package_submission.py            # both
    python bots/morpheus-rs/tools/package_submission.py --variant vendored
    python bots/morpheus-rs/tools/package_submission.py --no-smoke

Milestone M0.5 of docs/bots/morpheus-rs/rewrite-plan.md. Two archives come out,
and both are built every time on purpose:

**vendored** — sources, `Cargo.lock`, vendored crates, and a `build.sh` that
runs `cargo build --release --offline`. This is the intended submission: the
judge compiles it at intake on its own toolchain.

**static** — a prebuilt `x86_64-unknown-linux-musl` binary with `build.sh`
reduced to a no-op. This is R4's fallback for a sandbox that cannot build the
vendored tree (§9). The plan asks for it "from day one, so the fallback stays
tested rather than theoretical", which only holds if it is built and smoked on
every packaging run rather than written down and left alone.

Each archive is audited against the judge's limits through
`arena.bundle.check_limits` — the same code path that guards the Python bots,
so the two cannot drift — and then smoke-tested by extracting it, running its
`build.sh`, and driving a scripted frame through its `run.sh`.
"""
from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import subprocess
import sys
import tempfile
import zipfile
from dataclasses import dataclass
from pathlib import Path

BOT_DIR = Path(__file__).resolve().parents[1]
REPO = BOT_DIR.parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from arena.bundle import (  # noqa: E402
    MAX_FILES,
    MAX_UNPACKED_BYTES,
    MAX_ZIP_BYTES,
    BundleError,
    check_limits,
)

BUNDLES_DIR = REPO / "data" / "bundles"
MUSL_TARGET = "x86_64-unknown-linux-musl"
BINARY = "morpheus-rs"

# Fixed timestamp, matching arena.bundle: identical sources produce a
# byte-identical zip, so "did the submission change" is a checksum question.
_ZIP_DATE = (2020, 1, 1, 0, 0, 0)

# Source files the vendored variant ships. `rust-toolchain.toml` is
# deliberately **not** here: it pins an exact patch release, and a sandbox
# whose stable toolchain is any other patch would try to download the pinned
# one — over a network that does not exist at intake. The pin is a
# development-side guarantee that nothing newer than the sandbox's 1.97 gets
# used; shipping it would convert that guarantee into a build failure.
SOURCE_MEMBERS = ("Cargo.toml", "Cargo.lock")
SOURCE_TREES = ("crates",)

# Included when present. The model artifact does not exist yet (M3 adds the
# safetensors export), so this is a forward declaration, not dead code.
OPTIONAL_TREES = ("artifact",)

RUN_SH_VENDORED = """#!/usr/bin/env bash
# Submission launcher. No build here: build.sh already ran at intake.
set -euo pipefail
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export RAYON_NUM_THREADS=1
DIR="$(cd "$(dirname "$0")" && pwd)"
exec "$DIR/target/release/morpheus-rs"
"""

RUN_SH_STATIC = """#!/usr/bin/env bash
# Submission launcher for the static-binary variant: nothing was built at
# intake, the binary shipped in the zip.
set -euo pipefail
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export RAYON_NUM_THREADS=1
DIR="$(cd "$(dirname "$0")" && pwd)"
exec "$DIR/morpheus-rs"
"""

BUILD_SH_STATIC = """#!/usr/bin/env bash
# Nothing to build: this variant ships a self-contained static binary
# (x86_64-unknown-linux-musl). generals.bot's docs allow that shape, and it is
# the fallback for a sandbox where the vendored build does not work
# (rewrite-plan §9, R4).
set -euo pipefail
chmod +x "$(cd "$(dirname "$0")" && pwd)/morpheus-rs"
echo "[build] static binary, nothing to compile"
"""

# The `.cargo/config.toml` that goes in the vendored zip. The source
# replacement is what makes `--offline` work: cargo resolves every dependency
# out of `vendor/` instead of reaching for crates.io.
CARGO_CONFIG_VENDORED = """# Generated by tools/package_submission.py — do not edit in the zip.
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=x86-64-v3"]
"""

# One handshake and two frames on the smallest board the parser will accept.
# Enough to prove the binary speaks the protocol; not a game.
SMOKE_INPUT = "0 2 2\n" + ("1 1 1 1 1\n1 1\n1 1\n1 0\n0 0\n1 0\n0 0\n" * 2)
SMOKE_EXPECTED_LINES = 2


class PackageError(RuntimeError):
    """The submission cannot be built, or failed its own smoke test."""


@dataclass
class Package:
    variant: str
    zip_path: Path
    zip_bytes: int
    unpacked_bytes: int
    file_count: int
    smoked: bool
    smoke_note: str


def _cargo_env() -> dict[str, str]:
    """Environment with cargo on PATH, wherever rustup put it."""
    env = os.environ.copy()
    cargo_bin = Path.home() / ".cargo" / "bin"
    if cargo_bin.is_dir():
        env["PATH"] = f"{cargo_bin}{os.pathsep}{env.get('PATH', '')}"
    return env


def _run(command: list[str], cwd: Path, env: dict[str, str] | None = None) -> str:
    result = subprocess.run(
        command, cwd=str(cwd), env=env or _cargo_env(), capture_output=True, text=True
    )
    if result.returncode != 0:
        raise PackageError(
            f"{' '.join(command)} failed in {cwd}:\n{result.stdout}\n{result.stderr}"
        )
    return result.stdout


def _iter_source_files() -> list[tuple[Path, str]]:
    """(path, arcname) for everything the vendored variant compiles from."""
    members: list[tuple[Path, str]] = []
    for name in SOURCE_MEMBERS:
        path = BOT_DIR / name
        if not path.is_file():
            raise PackageError(f"missing {name}; run cargo build once first")
        members.append((path, name))
    for tree in SOURCE_TREES + OPTIONAL_TREES:
        root = BOT_DIR / tree
        if not root.is_dir():
            if tree in SOURCE_TREES:
                raise PackageError(f"missing {tree}/")
            continue
        for path in sorted(root.rglob("*")):
            if path.is_file() and "target" not in path.parts:
                members.append((path, str(path.relative_to(BOT_DIR))))
    return members


def _write_entry(zf: zipfile.ZipFile, arcname: str, data: bytes, *, mode: int) -> None:
    info = zipfile.ZipInfo(arcname, date_time=_ZIP_DATE)
    info.compress_type = zipfile.ZIP_DEFLATED
    # The judge executes run.sh and build.sh; a zip that loses the executable
    # bit produces a "permission denied" at intake that looks like a bot bug.
    info.external_attr = (mode & 0o7777) << 16
    zf.writestr(info, data)


def _vendor(workdir: Path) -> tuple[Path, int]:
    """
    Vendor the dependency graph. Returns (dir, file count) — often (dir, 0).

    Zero is the good answer and the reason the crate has no dependencies: the
    binding sandbox limit is 10,000 unpacked files, and `cargo vendor` over a
    fat graph clears it easily (rewrite-plan §1, R6).
    """
    vendor_dir = workdir / "vendor"
    vendor_dir.mkdir(parents=True, exist_ok=True)
    _run(["cargo", "vendor", "--versioned-dirs", str(vendor_dir)], cwd=BOT_DIR)
    return vendor_dir, sum(1 for p in vendor_dir.rglob("*") if p.is_file())


def build_vendored(out_path: Path, workdir: Path) -> tuple[Path, int]:
    vendor_dir, vendor_files = _vendor(workdir)
    build_sh = (BOT_DIR / "tools" / "submission" / "build.sh").read_bytes()

    with zipfile.ZipFile(out_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        _write_entry(zf, "run.sh", RUN_SH_VENDORED.encode(), mode=0o755)
        _write_entry(zf, "build.sh", build_sh, mode=0o755)
        _write_entry(zf, ".cargo/config.toml", CARGO_CONFIG_VENDORED.encode(), mode=0o644)
        for path, arcname in _iter_source_files():
            _write_entry(zf, arcname, path.read_bytes(), mode=0o644)
        for path in sorted(vendor_dir.rglob("*")):
            if path.is_file():
                arcname = f"vendor/{path.relative_to(vendor_dir)}"
                _write_entry(zf, arcname, path.read_bytes(), mode=0o644)
    return out_path, vendor_files


def _musl_rustflags() -> str | None:
    """
    Cross-linker flags, when the host cannot link ELF with its own `cc`.

    On macOS the system linker cannot produce ELF at all, so the build fails
    with an unreadable list of unknown `ld` options. `rust-lld` ships with the
    toolchain and links the musl target fine; it is pointed at explicitly
    rather than put in `.cargo/config.toml`, because on an x86 Linux host the
    ordinary `cc` is the better linker and needs no override.
    """
    if platform.system() == "Linux":
        return None
    sysroot = Path(_run(["rustc", "--print", "sysroot"], cwd=BOT_DIR).strip())
    # Asked of rustc rather than assembled from `platform.machine()`, which
    # says `arm64` on macOS where Rust's triple says `aarch64` — close enough
    # to look right and wrong enough to miss the file.
    host = ""
    for line in _run(["rustc", "-vV"], cwd=BOT_DIR).splitlines():
        if line.startswith("host:"):
            host = line.split(":", 1)[1].strip()
    if not host:
        raise PackageError("cannot read the host triple from `rustc -vV`")
    lld = sysroot / "lib" / "rustlib" / host / "bin" / "rust-lld"
    if not lld.is_file():
        raise PackageError(
            f"no rust-lld at {lld}; the static variant needs a cross linker "
            f"(or build it on an x86 Linux host)"
        )
    return f"-C linker-flavor=ld.lld -C linker={lld}"


def build_static(out_path: Path) -> tuple[Path, Path]:
    env = _cargo_env()
    flags = _musl_rustflags()
    if flags:
        env[f"CARGO_TARGET_{MUSL_TARGET.upper().replace('-', '_')}_RUSTFLAGS"] = (
            f"-C target-cpu=x86-64-v3 -C target-feature=+crt-static {flags}"
        )
    _run(
        ["cargo", "build", "--release", "--locked", "--target", MUSL_TARGET],
        cwd=BOT_DIR,
        env=env,
    )
    binary = BOT_DIR / "target" / MUSL_TARGET / "release" / BINARY
    if not binary.is_file():
        raise PackageError(f"no static binary at {binary}")

    with zipfile.ZipFile(out_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        _write_entry(zf, "run.sh", RUN_SH_STATIC.encode(), mode=0o755)
        _write_entry(zf, "build.sh", BUILD_SH_STATIC.encode(), mode=0o755)
        _write_entry(zf, BINARY, binary.read_bytes(), mode=0o755)
    return out_path, binary


def smoke(zip_path: Path, variant: str) -> tuple[bool, str]:
    """
    Extract the archive, run its build.sh, and speak the protocol to run.sh.

    This is the part that makes packaging a check rather than a hope: it runs
    the submitted bytes, from a directory with no repo around them, exactly as
    the judge will.
    """
    with tempfile.TemporaryDirectory(prefix="morpheus-rs-smoke-") as tmp:
        root = Path(tmp)
        with zipfile.ZipFile(zip_path) as zf:
            zf.extractall(root)
        for name in ("run.sh", "build.sh"):
            (root / name).chmod(0o755)

        if variant == "static" and platform.system() != "Linux":
            # An x86-64 ELF cannot run here. Verifying it *is* one is the most
            # this host can honestly claim; the rest waits for the sandbox.
            binary = root / BINARY
            header = binary.read_bytes()[:20]
            if header[:4] != b"\x7fELF" or header[18:20] != b"\x3e\x00":
                return False, "shipped binary is not an x86-64 ELF"
            return False, (
                f"built and verified as a static x86-64 ELF "
                f"({binary.stat().st_size} bytes); not runnable on "
                f"{platform.system()}/{platform.machine()}"
            )

        build = subprocess.run(
            ["bash", str(root / "build.sh")],
            cwd=str(root),
            env=_cargo_env(),
            capture_output=True,
            text=True,
        )
        if build.returncode != 0:
            return False, f"build.sh failed: {build.stderr[-500:]}"

        play = subprocess.run(
            ["bash", str(root / "run.sh")],
            cwd=str(root),
            input=SMOKE_INPUT,
            capture_output=True,
            text=True,
            timeout=120,
        )
        lines = [line for line in play.stdout.strip().splitlines() if line.strip()]
        if len(lines) != SMOKE_EXPECTED_LINES:
            return False, (
                f"run.sh replied {len(lines)} line(s), expected "
                f"{SMOKE_EXPECTED_LINES}: {play.stdout!r} {play.stderr[-300:]}"
            )
        for line in lines:
            parts = line.split()
            if len(parts) != 5 or not all(p.lstrip("-").isdigit() for p in parts):
                return False, f"malformed reply {line!r}"
        return True, f"built offline and replied {len(lines)} well-formed actions"


def package(variant: str, *, out_dir: Path, force: bool, run_smoke: bool) -> Package:
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"morpheus-rs-{variant}.zip"
    if out_path.exists() and not force:
        raise PackageError(f"{out_path} exists (pass --force to overwrite)")

    vendor_files = 0
    with tempfile.TemporaryDirectory(prefix="morpheus-rs-pkg-") as tmp:
        if variant == "vendored":
            _, vendor_files = build_vendored(out_path, Path(tmp))
        elif variant == "static":
            build_static(out_path)
        else:
            raise PackageError(f"unknown variant {variant!r}")

    zip_bytes, unpacked_bytes, file_count = check_limits(out_path)
    smoked, note = (False, "skipped")
    if run_smoke:
        smoked, note = smoke(out_path, variant)
    if variant == "vendored":
        note = f"{note}; {vendor_files} vendored file(s)"
    return Package(
        variant=variant,
        zip_path=out_path,
        zip_bytes=zip_bytes,
        unpacked_bytes=unpacked_bytes,
        file_count=file_count,
        smoked=smoked,
        smoke_note=note,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--variant",
        choices=("vendored", "static", "both"),
        default="both",
        help="default: both, so R4's fallback stays tested",
    )
    parser.add_argument("--out-dir", type=Path, default=BUNDLES_DIR)
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--no-smoke", action="store_true")
    args = parser.parse_args(argv)

    variants = ("vendored", "static") if args.variant == "both" else (args.variant,)
    results = []
    failures = []
    for variant in variants:
        try:
            built = package(
                variant,
                out_dir=args.out_dir,
                force=args.force,
                run_smoke=not args.no_smoke,
            )
        except (PackageError, BundleError) as exc:
            failures.append({"variant": variant, "error": str(exc)})
            continue
        results.append(
            {
                "variant": built.variant,
                "zip": str(built.zip_path),
                "zip_bytes": built.zip_bytes,
                "zip_limit": MAX_ZIP_BYTES,
                "unpacked_bytes": built.unpacked_bytes,
                "unpacked_limit": MAX_UNPACKED_BYTES,
                "files": built.file_count,
                "files_limit": MAX_FILES,
                "smoked": built.smoked,
                "smoke": built.smoke_note,
            }
        )

    print(json.dumps({"packages": results, "failures": failures}, indent=2))
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
