#!/usr/bin/env python3
"""Prove that a submission with real vendored crates builds with no network.

    python bots/morpheus-rs/tools/vendor_probe.py
    modal run scripts/morpheus_rs_modal_submission_smoke.py   # runs it offline on Linux

Produces `data/bundles/morpheus-rs-vendor-probe.zip` in exactly the shape a
real submission has.

**The gap this closes.** M0.5 proved `cargo build --release --offline` — with an
*empty* `vendor/`, because the crate has no dependencies. That is a much weaker
claim than it looks: with nothing to resolve, `--offline` cannot fail. It never
exercised `.cargo/config.toml` source replacement, a transitive graph, or a
build script running at intake. M3 adds an inference crate with ninety of them,
and finding out then that the path is broken is exactly what R4's tripwire is
supposed to prevent.

So the probe adds a dependency the shipped bot does not have, and picks one
that exercises the awkward parts:

* `sha2` has a **transitive graph** (`digest` → `block-buffer` →
  `generic-array` → `typenum`), so nested resolution is tested, not just a
  single flat crate.
* `typenum` has a **build script**, and `version_check` is a
  **build-dependency**. Build scripts compile and run during `build.sh`, at
  intake, offline — the failure mode most likely to be missed.
* It is small enough (565 files) that the probe stays fast.

The dependency lives only in the probe's scratch copy. `crates/core` stays
zero-dependency; nothing here changes the shipped binary or its lock file.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

BOT_DIR = Path(__file__).resolve().parents[1]
REPO = BOT_DIR.parents[1]
sys.path.insert(0, str(REPO))

from arena.bundle import BundleError, check_limits  # noqa: E402

BUNDLES_DIR = REPO / "data" / "bundles"
PROBE_ZIP = "morpheus-rs-vendor-probe.zip"
_ZIP_DATE = (2020, 1, 1, 0, 0, 0)

# Chosen for its shape, not its function — see the module docstring.
PROBE_DEPENDENCY = 'sha2 = { version = "0.10", default-features = false }'

# Uses the dependency for real. A probe whose dependency is unused would prove
# that cargo can *download* a crate, not that it can build one: an unreferenced
# dependency is still resolved, but its build script and its own dependencies
# may never be compiled.
PROBE_MAIN = """//! Vendor probe: a submission-shaped binary with a real dependency.
//!
//! Speaks enough of the wire protocol to be smoke-tested exactly like the bot,
//! and puts the vendored crate on the path that actually runs.
use sha2::{Digest, Sha256};

fn main() {
    let mut line = String::new();
    if std::io::stdin().read_line(&mut line).is_err() {
        return;
    }
    // Force the dependency to be linked and executed, not merely resolved.
    let mut hasher = Sha256::new();
    hasher.update(line.as_bytes());
    let digest = hasher.finalize();
    eprintln!("[vendor-probe] sha256 of handshake starts {:02x}", digest[0]);

    // Consume whole frames rather than replying per line: the smoke driver
    // sends a scalar line plus 3*H grid rows per turn and counts one reply
    // each, so a per-line responder would look like a protocol failure.
    let dims: Vec<usize> = line
        .split_ascii_whitespace()
        .filter_map(|t| t.parse().ok())
        .collect();
    let h = dims.get(1).copied().unwrap_or(0);

    use std::io::Write;
    loop {
        let mut buf = String::new();
        match std::io::stdin().read_line(&mut buf) {
            Ok(0) | Err(_) => return,
            Ok(_) => {}
        }
        if buf.trim().is_empty() {
            continue;
        }
        for _ in 0..3 * h {
            let mut row = String::new();
            if matches!(std::io::stdin().read_line(&mut row), Ok(0) | Err(_)) {
                return;
            }
        }
        println!("1 0 0 0 0");
        if std::io::stdout().flush().is_err() {
            return;
        }
    }
}
"""

RUN_SH = """#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
exec "$DIR/target/release/vendor-probe"
"""

BUILD_SH = """#!/usr/bin/env bash
# Same build step the real submission uses: offline, locked, no network.
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
cargo build --release --offline --locked --manifest-path "$DIR/Cargo.toml"
"""

CARGO_CONFIG = """# Generated by tools/vendor_probe.py — do not edit in the zip.
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=x86-64-v3"]
"""


def _cargo_env() -> dict[str, str]:
    env = os.environ.copy()
    cargo_bin = Path.home() / ".cargo" / "bin"
    if cargo_bin.is_dir():
        env["PATH"] = f"{cargo_bin}{os.pathsep}{env.get('PATH', '')}"
    return env


def _run(command: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        command, cwd=str(cwd), env=_cargo_env(), capture_output=True, text=True
    )


def _write_entry(zf: zipfile.ZipFile, arcname: str, data: bytes, mode: int) -> None:
    info = zipfile.ZipInfo(arcname, date_time=_ZIP_DATE)
    info.compress_type = zipfile.ZIP_DEFLATED
    info.external_attr = (mode & 0o7777) << 16
    zf.writestr(info, data)


def build_probe(out_path: Path, *, offline_check: bool = True) -> dict:
    with tempfile.TemporaryDirectory(prefix="vendor-probe-") as tmp:
        root = Path(tmp)
        (root / "src").mkdir()
        (root / "src" / "main.rs").write_text(PROBE_MAIN, encoding="utf-8")
        (root / "Cargo.toml").write_text(
            "[package]\n"
            'name = "vendor-probe"\nversion = "0.0.0"\nedition = "2021"\n\n'
            "[[bin]]\n"
            'name = "vendor-probe"\npath = "src/main.rs"\n\n'
            f"[dependencies]\n{PROBE_DEPENDENCY}\n",
            encoding="utf-8",
        )

        # Network is allowed *here* — this stands in for the developer machine
        # preparing the zip. Everything after this point must work without it.
        vendored = _run(["cargo", "vendor", "--versioned-dirs", "vendor"], root)
        if vendored.returncode != 0:
            raise BundleError(f"cargo vendor failed:\n{vendored.stderr[-1000:]}")

        vendor_dir = root / "vendor"
        vendor_files = [p for p in vendor_dir.rglob("*") if p.is_file()]

        result: dict = {
            "dependency": PROBE_DEPENDENCY,
            "vendored_files": len(vendor_files),
            "vendored_bytes": sum(p.stat().st_size for p in vendor_files),
            "crates": sum(1 for d in vendor_dir.iterdir() if d.is_dir()),
        }

        # Build offline right here, with the vendor config in place, before
        # packaging anything: a zip that cannot be built is not worth shipping
        # to a container to find that out.
        (root / ".cargo").mkdir()
        (root / ".cargo" / "config.toml").write_text(CARGO_CONFIG, encoding="utf-8")
        if offline_check:
            built = _run(
                ["cargo", "build", "--release", "--offline", "--locked"], root
            )
            result["local_build_ok"] = built.returncode == 0
            if built.returncode != 0:
                result["local_build_stderr"] = built.stderr[-2000:]

        out_path.parent.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(out_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            _write_entry(zf, "run.sh", RUN_SH.encode(), 0o755)
            _write_entry(zf, "build.sh", BUILD_SH.encode(), 0o755)
            _write_entry(zf, ".cargo/config.toml", CARGO_CONFIG.encode(), 0o644)
            for name in ("Cargo.toml", "Cargo.lock"):
                _write_entry(zf, name, (root / name).read_bytes(), 0o644)
            _write_entry(zf, "src/main.rs", PROBE_MAIN.encode(), 0o644)
            for path in sorted(vendor_files):
                _write_entry(
                    zf,
                    f"vendor/{path.relative_to(vendor_dir)}",
                    path.read_bytes(),
                    0o644,
                )

    zip_bytes, unpacked_bytes, file_count = check_limits(out_path)
    result.update(
        {
            "zip": str(out_path),
            "zip_bytes": zip_bytes,
            "unpacked_bytes": unpacked_bytes,
            "files": file_count,
        }
    )
    return result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=BUNDLES_DIR)
    parser.add_argument(
        "--no-local-build",
        action="store_true",
        help="package only; leave the offline build to the container",
    )
    args = parser.parse_args(argv)

    if shutil.which("cargo", path=_cargo_env()["PATH"]) is None:
        print("cargo not found", file=sys.stderr)
        return 2

    try:
        result = build_probe(
            args.out_dir / PROBE_ZIP, offline_check=not args.no_local_build
        )
    except BundleError as exc:
        print(json.dumps({"error": str(exc)}, indent=2))
        return 1

    print(json.dumps(result, indent=2))
    return 0 if result.get("local_build_ok", True) else 1


if __name__ == "__main__":
    raise SystemExit(main())
